#:schema https://raw.githubusercontent.com/YunoHost/apps/main/schemas/manifest.v2.schema.json

packaging_format = 2

id = "psotiz"
name = "Postiz"
description.en = "📨 The ultimate agentic social media scheduling tool"
description.fr = "📨 L'outil ultime de planification agentique des réseaux sociaux"
version = "2.21.8~ynh1"

maintainers = ["CodeShakingSheep"]

[upstream]
license = "AGPL-3.0-only"
website = "https://postiz.com"
admindoc = "https://docs.postiz.com"
code = "https://github.com/gitroomhq/postiz-app"

[integration]
yunohost = ">= 12.1.17"
helpers_version = "2.1"
architectures = "all"
multi_instance = true

ldap = false
sso = false

disk = "2000M"
ram.build = "4096M"
ram.runtime = "2048M"

[install]
    [install.domain]
    type = "domain"

    #[install.path]
    #type = "path"
    #default = "/example"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

    [install.language]
    ask.en = "Choose the application language"
    ask.fr = "Choisissez la langue de l'application"
    type = "select"
    choices = ["fr", "en"]
    default = "fr"

    [install.admin]
    type = "user"

    [install.password]
    help.en = "Use the help field to add an information for the admin about this question."
    help.fr = "Utilisez le champ aide pour ajouter une information à l'intention de l'administrateur à propos de cette question."
    type = "password"

[resources]

    [resources.sources]

    [resources.sources.main]
    url = "https://github.com/gitroomhq/postiz-app/archive/refs/tags/v2.21.8.tar.gz"
    sha256 = "89d1caaf83df9baf4abcc16ddd2b935607c086aa84ac097906b481e213d67a19"

    autoupdate.strategy = "latest_github_release"

    [resources.system_user]

    [resources.install_dir]

    [resources.data_dir]

    [resources.permissions]
    main.url = "/"

    [resources.ports]

    [resources.apt]
    packages = ""

    [resources.database]
    type = "postgresql"

    [resources.nodejs]
    version = "24"
