#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source /usr/share/yunohost/helpers

#=================================================
# STOP SYSTEMD SERVICE
#=================================================
ynh_script_progression "Stopping $app's systemd services..."

ynh_systemctl --service="$app-backend" --action="stop"
ynh_systemctl --service="$app-frontend" --action="stop"
ynh_systemctl --service="$app-orchestrator" --action="stop"
ynh_systemctl --service="$app-temporal" --action="stop"

#=================================================
# MODIFY URL IN NGINX CONF
#=================================================
ynh_script_progression "Updating NGINX web server configuration..."

ynh_config_change_url_nginx

#=================================================
# SPECIFIC MODIFICATIONS
#=================================================

jwt_secret=$(ynh_app_setting_get --key=jwt_secret)
redis_db=$(ynh_app_setting_get --key=redis_db)

ynh_config_add --template=".env" --destination="$install_dir/.env"

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting $app's systemd service..."

# Start systemd services
ynh_systemctl --service="$app-backend" --action="start"
ynh_systemctl --service="$app-frontend" --action="start"
ynh_systemctl --service="$app-orchestrator" --action="start"
ynh_systemctl --service="$app-temporal" --action="start"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Change of URL completed for $app"
