#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source /usr/share/yunohost/helpers

#=================================================
# INITIALIZE AND STORE SETTINGS
#=================================================

jwt_secret=$(ynh_string_random --length=24)
redis_db=$(ynh_redis_get_free_db)

ynh_app_setting_set --key=jwt_secret --value=$jwt_secret
ynh_app_setting_set --key=redis_db --value=$redis_db

#=================================================
# INSTALL DEPENDENCIES
#=================================================
ynh_script_progression "Installing dependencies..."

PNPM_VERSION=$(sed -n 's/.*"packageManager":\s*"pnpm@\([^"]*\)".*/\1/p' $install_dir/package.json)
npm install -g "pnpm@${PNPM_VERSION}"
# https://github.com/pnpm/pnpm/issues/8949
#npm install --global corepack@latest
#corepack enable pnpm
#corepack use pnpm@latest

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Setting up source files..."

# Download, check integrity, uncompress and patch the source from manifest.toml
ynh_setup_source --dest_dir="$install_dir"

# Download and extract temporal
ynh_setup_source --source_id="temporal" --dest_dir="$install_dir/temporal"

#=================================================
# APP INITIAL CONFIGURATION
#=================================================
ynh_script_progression "Adding $app's configuration files..."

ynh_config_add --template=".env" --destination="$install_dir/.env"

#=================================================
# INSTALL POSTIZ
#=================================================
ynh_script_progression "Building the app..."

pushd $install_dir
    ynh_script_progression "Installin the app..."

    ynh_exec_as_app NODE_OPTIONS="--max-old-space-size=4096" pnpm install 

    ynh_script_progression "Building the app..."

    ynh_exec_as_app NODE_OPTIONS="--max-old-space-size=4096" TURBO_TELEMETRY_DISABLED=1 pnpm build --concurrency=1 

    ynh_script_progression "Running DB migrations of the app..."

    ynh_exec_as_app pnpm run prisma-db-push
popd

#chown -R $app:$app $install_dir

#=================================================
# SYSTEM CONFIGURATION
#=================================================
ynh_script_progression "Adding system configurations related to $app..."

ynh_config_add_nginx

# Backend
ynh_config_add_systemd --service="$app-backend" --template="postiz-backend.service"
yunohost service add "$app-backend" --description="Postiz backend" --log="/var/log/$app/$app-backend.log"

#Frontend
ynh_config_add_systemd --service="$app-frontend" --template="postiz-frontend.service"
yunohost service add "$app-frontend" --description="Postiz frontend" --log="/var/log/$app/$app-frontend.log"

# Orchestrator
ynh_config_add_systemd --service="$app-orchestrator" --template="postiz-orchestrator.service"
yunohost service add "$app-orchestrator" --description="Postiz orchestrator" --log="/var/log/$app/$app-orchestrator.log"

# Temporal
ynh_config_add_systemd --service="$app-temporal" --template="postiz-temporal.service"
yunohost service add "$app-temporal" --description="Postiz temporal" --log="/var/log/$app/$app-temporal.log"

#=================================================
# START SYSTEMD SERVICES
#=================================================
ynh_script_progression "Starting $app's systemd services..."

# Start systemd services
ynh_systemctl --service="$app-backend" --action="start"
ynh_systemctl --service="$app-frontend" --action="start"
ynh_systemctl --service="$app-orchestrator" --action="start"
ynh_systemctl --service="$app-temporal" --action="start"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Installation of $app completed"
