#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source /usr/share/yunohost/helpers

#=================================================
# REMOVE SYSTEM CONFIGURATION
#=================================================
ynh_script_progression "Removing system configurations related to $app..."

yunohost service remove "$app-backend"
yunohost service remove "$app-frontend"
yunohost service remove "$app-orchestrator"
yunohost service remove "$app-temporal"

ynh_config_remove_systemd "$app-backend"
ynh_config_remove_systemd "$app-frontend"
ynh_config_remove_systemd "$app-orchestrator"
ynh_config_remove_systemd "$app-temporal"

ynh_config_remove_nginx

ynh_redis_remove_db $redis_db

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Removal of $app completed"
