#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source /usr/share/yunohost/helpers

#=================================================
# RESTORE THE APP MAIN DIR
#=================================================
ynh_script_progression "Restoring the app main directory..."

ynh_restore "$install_dir"

chown -R "$app:www-data" "$install_dir"

ynh_script_progression "Reinstalling pnpm..."

PNPM_VERSION=$(sed -n 's/.*"packageManager":\s*"pnpm@\([^"]*\)".*/\1/p' $install_dir/package.json)
npm install --global corepack@latest
corepack enable pnpm
corepack use pnpm@${PNPM_VERSION}

#=================================================
# RESTORE THE DATA DIRECTORY
#=================================================
ynh_script_progression "Restoring the data directory..."

ynh_restore "$data_dir"

chown -R "$app:$app" "$data_dir"

#=================================================
# RESTORE THE POSTGRESQL DATABASE
#=================================================
ynh_script_progression "Restoring the PostgreSQL database..."

ynh_psql_db_shell < ./db.sql

#=================================================
# RESTORE SYSTEM CONFIGURATION
#=================================================
ynh_script_progression "Restoring system configurations related to $app..."

ynh_restore "/etc/nginx/conf.d/$domain.d/$app.conf"

ynh_restore /var/log/$app
chown $app:$app /var/log/$app

ynh_restore "/etc/systemd/system/$app-backend.service"
systemctl enable "$app-backend.service" --quiet
ynh_restore "/etc/systemd/system/$app-frontend.service"
systemctl enable "$app-frontend.service" --quiet
ynh_restore "/etc/systemd/system/$app-orchestrator.service"
systemctl enable "$app-orchestrator.service" --quiet
ynh_restore "/etc/systemd/system/$app-temporal.service"
systemctl enable "$app-temporal.service" --quiet

yunohost service add "$app-backend" --description="Postiz backend" --log="/var/log/$app/$app-backend.log"
yunohost service add "$app-frontend" --description="Postiz frontend" --log="/var/log/$app/$app-frontend.log"
yunohost service add "$app-orchestrator" --description="Postiz orchestrator" --log="/var/log/$app/$app-orchestrator.log"
yunohost service add "$app-temporal" --description="Postiz temporal" --log="/var/log/$app/$app-temporal.log"

#=================================================
# RESTORE VARIOUS FILES
#=================================================

ynh_restore "/var/log/$app/"

#=================================================
# RELOAD NGINX AND PHP-FPM OR THE APP SERVICE
#=================================================
ynh_script_progression "Reloading NGINX web server and $app's service..."

# Start systemd services
ynh_systemctl --service="$app-backend" --action="start"
ynh_systemctl --service="$app-frontend" --action="start"
ynh_systemctl --service="$app-orchestrator" --action="start"
ynh_systemctl --service="$app-temporal" --action="start"

ynh_systemctl --service=nginx --action=reload

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Restoration completed for $app"
